title: Volodymyr B.
logo: https://economictimes.indiatimes.com/blogs/wp-content/uploads/2017/08/cyber-law-thinkstock.jpg
description: Future lawyer
show_downloads: 
google_analytics:
theme: jekyll-theme-minimal
